# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2021-12-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import mascota.models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to=mascota.models.upload_location, width_field=200),
        ),
    ]
