# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2021-12-03 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import mascota.models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_mascota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=mascota.models.upload_location),
        ),
    ]
