# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2022-05-04 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20220504_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='raza',
            name='comportamiento',
            field=models.CharField(default='tranquilo', max_length=250),
            preserve_default=False,
        ),
    ]
